module.exports = {
    ADD_MENU_CARD: 'ADD_MENU_CARD',
    ADD_MENU_ITEM: 'ADD_MENU_ITEM',
    OPEN_ADD_MENU_CARD_DIALOG: 'OPEN_ADD_MENU_CARD_DIALOG',
    TOGGLE_QR_DIALOG: 'TOGGLE_QR_DIALOG',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    SET_ALERT: 'SET_ALERT',
    SET_LOCAL_INPUT: 'SET_LOCAL_INPUT',
    SET_INPUT: 'SET_INPUT',
    SET_CHECKIN_REF: 'SET_CHECKIN_REF',
    SET_SELECTED_CARD_ID : 'SET_SELECTED_CARD_ID',
    SET_CURRENT_STEP: 'SET_CURRENT_STEP'
}