module.exports = {
    ADD_MENU_CARD: 'ADD_MENU_CARD',
    ADD_MENU_ITEM: 'ADD_MENU_ITEM',
    OPEN_ADD_MENU_CARD_DIALOG: 'OPEN_ADD_MENU_CARD_DIALOG',
    TOGGLE_QR_DIALOG: 'TOGGLE_QR_DIALOG',
    SET_QR_DIALOG_ID: 'SET_QR_DIALOG_ID'
}