module.exports = {
    checkinRef: "",
    selectedCardMenuRef: "",
    currentStep: "",
    errorMessage: "",
    alertMessage: "",
    menuCards: [],
    consumers: [],
    menuCardItems: [],
    toggleAddMenuDialog: false,
    toggleAddMenuItem: false,
    toggleQrDialog: false,
    isLoading: false,
    menuName: "",
    menuLink: "",
    ownLinkControl: false,
    qrCodeControl: false,
    verifiedUser: false,
    userInfo: [],
    publicInfo: []
}