module.exports = {
    // checkinRef: "",
    // selectedCardMenuRef: "",
    // currentStep: "",
    // buttonTracker: "",
    // errorMessage: "",
    // alertMessage: "",
    // menuCards: [],
    // menuCardItems: [],
    // menuCardItemCounter: 0,
    // consumers: [],
    toggleAddMenuDialog: false,
    toggleAddMenuItem: false,
    toggleQrDialog: false,
    toggleItemImageDialog: false,
    isLoading: false,

    // menuName: "",
    // menuLink: "",
    // menuCardTitle: "",
    // itemTitle: "",
    // itemPrice: "",
    // ownLinkControl: false,
    // qrCodeControl: false,
    // userInfo: [],
    publicInfo: [],
    // itemImage: "",
    // itemImageFile: "",

}